// Targeted re-capture of the whisper peak → Isaiah 41:10 (live). node scripts/capture-whisper.mjs
import { chromium } from 'playwright';
import fs from 'fs';
import path from 'path';
const URL = process.env.SELAH_URL || 'http://localhost:8099/index.html';
const OUT = path.resolve('capture');
const VIEW = { width: 1920, height: 1080 };
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
const dir = path.join(OUT, 'whisper2');
fs.mkdirSync(dir, { recursive: true });
const browser = await chromium.launch();
const context = await browser.newContext({ viewport: VIEW, deviceScaleFactor: 1, recordVideo: { dir, size: VIEW } });
const page = await context.newPage();
await page.goto(URL, { waitUntil: 'networkidle' });
await page.evaluate(() => { try { playing = true; window.loop = false; } catch (e) {} });
await wait(2200);
await page.evaluate(() => { try { act = 'run'; playing = true; idx = 3; ecgStart(); render(WORKOUTS.run[2], 2); } catch (e) {} });
await wait(2400);
await page.evaluate(() => { try { $('#face').style.opacity = '0.12'; } catch (e) {} });
await wait(1500);
await page.evaluate(() => { try { discern("I'm scared"); } catch (e) {} });
await wait(7500);
await context.close();
const f = fs.readdirSync(dir).filter((x) => x.endsWith('.webm'))[0];
fs.renameSync(path.join(dir, f), path.join(OUT, 'whisper.webm'));
fs.rmSync(dir, { recursive: true, force: true });
fs.copyFileSync(path.join(OUT, 'whisper.webm'), path.resolve('video/public/whisper.webm'));
await browser.close();
console.log('DONE -> whisper.webm');
